[pytest]
testpaths = Tests
python_files = test_*.py *_test.py
python_classes = Test
python_functions = test_*

markers =
    ui: UI tests
    api: API tests

addopts =
    -v
    -s
    --tb=short
    --alluredir=allure-results
    --strict-markers
